[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5001
  publish = "public"
  functions = "netlify/functions"

# Function settings
[functions]
  # Increase the timeout for functions
  node_bundler = "esbuild"
  external_node_modules = ["express"]

# Primary redirect to the simplified serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/simple-server"
  status = 200
  # Fallback if the function fails or times out
  force = true

# Fallback for server errors
[[redirects]]
  from = "/*"
  to = "/error.html"
  status = 500
  force = false

# Redirect for the test function
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

# Redirect for the simple server
[[redirects]]
  from = "/simple/*"
  to = "/.netlify/functions/simple-server"
  status = 200
  force = true

# Redirect for health check
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server/api/health"
  status = 200
  force = true
